### ISSUE TITLE
Git and firewall issues with consul_cluster module

### ISSUE THREAD

**Issue by darrow** [hashicorp/terraform-google-vault#6]
I ran into two issues, one of which I was able to resolve.

1. The format for pulling the consul_cluster module is ssh://git.  I had to rewrite the source to use HTTP to pull the module.  

2. With terraform plan I can't get past issues for the healthcheck.  What is needed here?

# Init with unmodified main.tf

$ terraform init
Initializing modules...
- module.vault_cluster
  Getting source "../../modules/vault-cluster"
- module.consul_cluster
  Getting source "git::git@github.com:hashicorp/terraform-google-consul.git//modules/consul-cluster?ref=v0.0.1"
Error downloading modules: Error loading modules: error downloading 'ssh://git@github.com/hashicorp/terraform-google-consul.git?ref=v0.0.1': /usr/local/bin/git exited with 128: Cloning into '.terraform/modules/97d73d57bf296cc4c3f5ff801d526b81'...
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

# init with modified main.tf

$ terraform init
Initializing modules...
- module.vault_cluster
- module.consul_cluster
  Getting source "github.com/hashicorp/terraform-google-consul//modules/consul-cluster?ref=v0.0.1"

Initializing provider plugins...
- Checking for available provider plugins on https://releases.hashicorp.com...
- Downloading plugin for provider "google" (1.2.0)...
- Downloading plugin for provider "template" (1.0.0)...

The following providers do not have any version constraints in configuration,
so the latest version was installed.

To prevent automatic upgrades to new major versions that may contain breaking
changes, it is recommended to add version = "..." constraints to the
corresponding provider blocks in configuration, with the constraint strings
suggested below.

* provider.google: version = "~> 1.2"
* provider.template: version = "~> 1.0"

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.

# terraform plan ends with an output problem for the healthchecks. 
$ terraform plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

data.template_file.startup_script_vault: Refreshing state...
data.template_file.startup_script_consul: Refreshing state...

------------------------------------------------------------------------

Error: Error running plan: 2 error(s) occurred:

* module.vault_cluster.output.firewall_rule_allow_inbound_health_check_url: Resource 'google_compute_firewall.allow_inboud_health_check' not found for variable 'google_compute_firewall.allow_inboud_health_check.self_link'
* module.vault_cluster.output.firewall_rule_allow_inbound_health_check_id: Resource 'google_compute_firewall.allow_inboud_health_check' not found for variable 'google_compute_firewall.allow_inboud_health_check.id'

# versions
$ terraform version
Terraform v0.11.0
+ provider.google v1.2.0
+ provider.template v1.0.0

**Comment by josh-padnick** [comment]
@darrow The issue is that you're using Terraform v0.11.0, but there's an [open discussion](https://github.com/hashicorp/terraform/issues/16726) about how to handle outputs with resources that can potentially have a `count = 0`.

I've posted a fix at #7 if you'd like to see how to resolve this, but per that Pull Request, I'd prefer to wait for the discussion to resolve before making any changes. Aside from the labor required to update all outputs of all modules that involve resources that could have `count = 0`, the new syntax is also less readable, so I'd prefer to hold off on a change for now.

Regarding the git issue, this is a public repo (hence your ability to submit this issue!), but you're also the second person to report this. Nevertheless, I believe this is a local configuration problem. There are many online threads about this ([example](https://stackoverflow.com/questions/16245606/could-not-read-from-remote-repository)). 

That being said I can't think of a downside to using HTTP URLs, so I'm open to switching. Of course, Terraform 0.11.x supports [improved module registry integration](https://www.hashicorp.com/blog/hashicorp-terraform-0-11#registry_integration), so using the new short URLs is the best approach, but that breaks compatibility with Terraform < 0.11.x, which seems too high a price to pay right now.

**Comment by brikis98** [comment]
> That being said I can't think of a downside to using HTTP URLs

There are no major downsides for public repos, but for private repos, HTTP URLs require you to include a username + password, whereas Git URLs will use SSH keys. Probably doesn't matter for this open source repo, but just thought I'd mention it.

**Comment by josh-padnick** [comment]
Ah, that's a good point. In that case, I'd rather stick with Git URLs so that Users can learn to standardize on a single URL format.

**Comment by darrow** [comment]
@josh-padnick thanks, your fix in #7 worked for me.
